environment:
  JAVA_HOME: C:\Program Files\Java\jdk12
install:
  - java -version
build_script:
  - cd HA01_CLI && gradlew.bat -i -S --no-daemon build
test_script:
  - cd HA01_CLI && gradlew.bat -i -S --no-daemon check
cache:
  - C:\Users\appveyor\.gradle
